---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: client-intents-for-server
  namespace: otterize-tutorial-mapper
spec:
  workload:
    name: server
    kind: Deployment
  targets:
    - internet:
        domains:
          - registry.npmjs.org
